nfephp-org/sped-esocial

- .gitignore
- .scrutinizer.yml
- examples/Fake/FaketestEvtAvPrevio.php
- src/Factories/EvtAvPrevio.php
FaketestEvtAvPrevio ok, falta o testJsonFaketestEvtAvPrevio
> FaketestEvtAvPrevio

- examples/Fake/FaketestEvtAvPrevio.php
- examples/Fake/FaketestEvtExclusao.php
- examples/schemas/testJsonSchemaEvtAvPrevio.php
- examples/schemas/testJsonSchemaEvtExclusao.php
- jsonSchemes/v02_03_00/evtAvPrevio.schema
- jsonSchemes/v02_03_00/evtExclusao.schema
- src/Factories/EvtAvPrevio.php
- src/Factories/EvtExclusao.php
> evtavprevio finalizado

- examples/Fake/FaketestEvtFechaEvPer.php
- examples/schemas/testJsonSchemaEvtExclusao.php
- examples/schemas/testJsonSchemaEvtFechaEvPer.php
- examples/schemas/testJsonSchemaEvtReabreEvPer.php
- jsonSchemes/v02_03_00/evtExclusao.schema
- jsonSchemes/v02_03_00/evtFechaEvPer.schema
- jsonSchemes/v02_03_00/evtReabreEvPer.schema
- src/Factories/EvtFechaEvPer.php
FaketestEvtFechaEvPer finalizado
> FaketestEvtFechaEvPer finalizado

- examples/Fake/FaketestEvtBenPrRP.php
- examples/schemas/testJsonSchemaEvtBenPrRP.php
- jsonSchemes/v02_03_00/evtBenPrRP.schema
- schemes/v02_03_00/evtBenPrRP.xsd
- src/Factories/EvtBenPrRP.php
> evtBenPrRP finalizado

- examples/Fake/FaketestEvtComProd.php
- examples/schemas/testJsonSchemaEvtComProd.php
- jsonSchemes/v02_03_00/evtComProd.schema
- src/Factories/EvtComProd.php
> EvtComProd finalizado

- examples/Fake/FaketestEvtContrSindPatr.php
- examples/schemas/testJsonSchemaEvtContrSindPatr.php
- jsonSchemes/v02_03_00/evtContrSindPatr.schema
- src/Factories/EvtContrSindPatr.php
> EvtContrSindPatr finalizado

- examples/Fake/FaketestEvtContratAvNP.php
- examples/schemas/testJsonSchemaEvtContratAvNP.php
- jsonSchemes/v02_03_00/evtContratAvNP.schema
- src/Factories/EvtContratAvNP.php
> evtContratAvNP finalizado

- examples/Fake/FaketestEvtInfoComplPer.php
- examples/schemas/testJsonSchemaEvtInfoComplPer.php
- jsonSchemes/v02_03_00/evtInfoComplPer.schema
- src/Factories/EvtInfoComplPer.php
> EvtInfoComplPer finalizado

- examples/Fake/FaketestEvtCdBenPrRP.php
- examples/schemas/testJsonSchemaEvtCdBenPrRP.php
- examples/schemas/testJsonSchemaEvtTSVAltContr.php
- jsonSchemes/v02_03_00/evtCdBenPrRP.schema
- jsonSchemes/v02_03_00/evtTSVAltContr.schema
- schemes/v02_03_00/evtCdBenPrRP.xsd
- src/Factories/EvtCdBenPrRP.php
> EvtCdBenPrRP finalizado

- src/Factories/EvtBenPrRP.php
- src/Factories/EvtInfoEmpregador.php
- src/Factories/EvtPgtos.php
- src/Factories/EvtRemun.php
- src/Factories/EvtRmnRPPS.php
- src/Factories/EvtTabAmbiente.php
- src/Factories/EvtTabCargo.php
- src/Factories/EvtTabCarreira.php
- src/Factories/EvtTabEquipamento.php
- src/Factories/EvtTabEstab.php
- src/Factories/EvtTabFuncao.php
- src/Factories/EvtTabHorTur.php
- src/Factories/EvtTabLotacao.php
- src/Factories/EvtTabOperPort.php
- src/Factories/EvtTabProcesso.php
- src/Factories/EvtTabRubrica.php
Correção no constructor das factories que não estavam sobrescrevendo $date
> [UPD] Correção na sobrescrita do Constructor

- README.md
Atualização do README com alteração do cronograma para Grupo 4 - Entes públicos
> Atualiza cronograma grupo 4 - entes públicos

- src/Factories/Traits/TraitS1298.php
o arquivo evtReabreEvPer.xsd já estava atualizado pelo site do eSocial
> Incluir builder evento S-1298 layout S.1.0.0

- examples/schemes/v_S_01_00_00/s2220_JsonSchemaEvtMonit.php
- jsonSchemes/v_S_01_00_00/evtMonit.schema
- src/Factories/Traits/TraitS2220.php
Correção da issue #365, na qual o 2220 não estava ponderando o nrRecibo
> Ajustes 2220 #365

- examples/Fake/v_S_01_00_00/Fake_s2200_EvtAdmissao.php
- jsonSchemes/v_S_01_00_00/evtAltContratual.schema
[2206_altContratual_vinculo_infoRegimeTrab_infoEstatutario_tpPlanRP]( https://www.gov.br/esocial/pt-br/documentacao-tecnica/leiautes-esocial-nt-03-2021-html/index.html#2206_altContratual_vinculo_infoRegimeTrab_infoEstatutario_tpPlanRP )
Tipo de plano de segregação da massa.
Valores válidos:
0 - Sem segregação da massa
1 - Fundo em capitalização
2 - Fundo em repartição
3 - Mantido pelo Tesouro
> Plano de segregação de massa novos valores válidos

- src/Factories/Traits/TraitS2300.php
- src/Factories/Traits/TraitS2306.php
**Campos:** nmRazao, dscLograd, nrLograd, bairro, cep, codMunic
**Validação:** Preenchimento obrigatório e exclusivo se o campo cnpjInstEnsino não estiver preenchido.
https://www.gov.br/esocial/pt-br/documentacao-tecnica/leiautes-esocial-nt-04-2021-html/index.html#2300_infoTSVInicio_infoComplementares_infoEstagiario_instEnsino
> Validação de Instituição de ensino - Estagiário

- src/Factories/Traits/TraitS2405.php
Falta de assinatura no final do evento
> Falta da assinatura

- schemes/v_S_01_00_00/evtExpRisco.xsd
Sobre a PR #447 faltou só uma validação no xsd. Ajustado aqui nessa PR
> Validação cpfResp

- jsonSchemes/v_S_01_00_00/evtTSVAltContr.schema
**nmRazao** - Informar a razão social.
**Validação:** Preenchimento obrigatório e exclusivo se o campo cnpjInstEnsino não estiver preenchido.
> Update evtTSVAltContr.schema S2306

- examples/schemes/v_S_01_00_00/s2200_JsonSchemaEvtAdmissao.php
- jsonSchemes/v_S_01_00_00/evtAdmissao.schema
Acrescentando o tipo "null" como permitido no campo 105 (dtIngrCargo) do evento "S-2200 - Cadastramento Inicial do Vínculo e Admissão/Ingresso de Trabalhador"
> #459 - Issue

- schemes/v_S_01_00_00/evtAltContratual.xsd
- src/Factories/Traits/TraitS2206.php
#461 - Atualização validações de elementos <xs:element name="infoRegimeTrab" minOccurs="0"> como opcional no arquivo schemes/v_S_01_00_00/evtAltContratual.xsd
> #461 - Atualização validações no arquivo evtAltContratual.xsd

- schemes/v_S_01_01_00/evtAdmissao.xsd
- schemes/v_S_01_01_00/evtAfastTemp.xsd
- schemes/v_S_01_01_00/evtAltCadastral.xsd
- schemes/v_S_01_01_00/evtBasesFGTS.xsd
- schemes/v_S_01_01_00/evtBasesTrab.xsd
- schemes/v_S_01_01_00/evtCAT.xsd
- schemes/v_S_01_01_00/evtCdBenIn.xsd
- schemes/v_S_01_01_00/evtContProc.xsd
- schemes/v_S_01_01_00/evtDeslig.xsd
- schemes/v_S_01_01_00/evtProcTrab.xsd
- schemes/v_S_01_01_00/evtTSVTermino.xsd
- schemes/v_S_01_01_00/tipos.xsd
Esquemas XSD v. S-1.1 (até NT 01/2023) - versão em produção (09.02.2023)
> Esquemas XSD v. S-1.1 - 09.02.2023

- src/Factories/Traits/TraitS2300.php
Ajustado campo nmRazao TraitS2300
> ajuste instituicaoEnsino->rmRazao empty

- src/Factories/Traits/TraitS2299.php
O campo indRRA não é obrgatório.
> Ajuste TraisS2299 indRRA

- examples/schemes/v_S_01_02_00/s2200_JsonSchemaEvtAdmissao.php
- examples/schemes/v_S_01_02_00/s2206_JsonSchemaEvtAltContratual.php
- jsonSchemes/v_S_01_02_00/evtAdmissao.schema
- jsonSchemes/v_S_01_02_00/evtAltContratual.schema
Permitindo valo null campo nrinsc.
Ajuste no jsonSchemes evtAltContratual.
> Corrigindo evtAdmissao e evtAltContratual

- jsonSchemes/v_S_01_02_00/evtAdmissao.schema
- jsonSchemes/v_S_01_02_00/evtCdBenefIn.schema
- jsonSchemes/v_S_01_02_00/evtTSVInicio.schema
- src/Factories/Traits/TraitS2300.php
- src/Factories/Traits/TraitS2400.php
Fix
A biblioteca não está considerando o envio do campo descrDep (S2300 e S2400).
A biblioteca não está validando o campo descrDep (S2200, S2300 e S2400).
> Fix - Envio do campo descrDep

- src/Factories/Traits/TraitS1210.php
Correção na TraitS1210. A verificação do plansaude e inforeembmed
estava dentro do If da InfoIRCR
> Correção na TraitS1210 na Versão 1.3.0
